module Constants
  EXIT_FAILURE     = 1
  RTE_LOG_LEVEL    = RTE_LOG_INFO
  RTE_LOG_DP_LEVEL = RTE_LOG_INFO
  NULL             = nil

  ETH_RSS_IPV4               = 1_u32 << RTE_ETH_FLOW_IPV4
  ETH_RSS_FRAG_IPV4          = 1_u32 << RTE_ETH_FLOW_FRAG_IPV4
  ETH_RSS_NONFRAG_IPV4_TCP   = 1_u32 << RTE_ETH_FLOW_NONFRAG_IPV4_TCP
  ETH_RSS_NONFRAG_IPV4_UDP   = 1_u32 << RTE_ETH_FLOW_NONFRAG_IPV4_UDP
  ETH_RSS_NONFRAG_IPV4_SCTP  = 1_u32 << RTE_ETH_FLOW_NONFRAG_IPV4_SCTP
  ETH_RSS_NONFRAG_IPV4_OTHER = 1_u32 << RTE_ETH_FLOW_NONFRAG_IPV4_OTHER
  ETH_RSS_IPV6               = 1_u32 << RTE_ETH_FLOW_IPV6
  ETH_RSS_FRAG_IPV6          = 1_u32 << RTE_ETH_FLOW_FRAG_IPV6
  ETH_RSS_NONFRAG_IPV6_TCP   = 1_u32 << RTE_ETH_FLOW_NONFRAG_IPV6_TCP
  ETH_RSS_NONFRAG_IPV6_UDP   = 1_u32 << RTE_ETH_FLOW_NONFRAG_IPV6_UDP
  ETH_RSS_NONFRAG_IPV6_SCTP  = 1_u32 << RTE_ETH_FLOW_NONFRAG_IPV6_SCTP
  ETH_RSS_NONFRAG_IPV6_OTHER = 1_u32 << RTE_ETH_FLOW_NONFRAG_IPV6_OTHER
  ETH_RSS_L2_PAYLOAD         = 1_u32 << RTE_ETH_FLOW_L2_PAYLOAD
  ETH_RSS_IPV6_EX            = 1_u32 << RTE_ETH_FLOW_IPV6_EX
  ETH_RSS_IPV6_TCP_EX        = 1_u32 << RTE_ETH_FLOW_IPV6_TCP_EX
  ETH_RSS_IPV6_UDP_EX        = 1_u32 << RTE_ETH_FLOW_IPV6_UDP_EX
  ETH_RSS_PORT               = 1_u32 << RTE_ETH_FLOW_PORT
  ETH_RSS_VXLAN              = 1_u32 << RTE_ETH_FLOW_VXLAN
  ETH_RSS_GENEVE             = 1_u32 << RTE_ETH_FLOW_GENEVE
  ETH_RSS_NVGRE              = 1_u32 << RTE_ETH_FLOW_NVGRE

  ETH_RSS_IP         = (ETH_RSS_IPV4 | ETH_RSS_FRAG_IPV4 | ETH_RSS_NONFRAG_IPV4_OTHER | ETH_RSS_IPV6 | ETH_RSS_FRAG_IPV6 | ETH_RSS_NONFRAG_IPV6_OTHER | ETH_RSS_IPV6_EX)
  ETH_RSS_UDP        = (ETH_RSS_NONFRAG_IPV4_UDP | ETH_RSS_NONFRAG_IPV6_UDP | ETH_RSS_IPV6_UDP_EX)
  ETH_RSS_TCP        = (ETH_RSS_NONFRAG_IPV4_TCP | ETH_RSS_NONFRAG_IPV6_TCP | ETH_RSS_IPV6_TCP_EX)
  ETH_RSS_SCTP       = (ETH_RSS_NONFRAG_IPV4_SCTP | ETH_RSS_NONFRAG_IPV6_SCTP)
  ETH_RSS_TUNNEL     = (ETH_RSS_VXLAN | ETH_RSS_GENEVE | ETH_RSS_NVGRE)
  ETH_RSS_PROTO_MASK = (ETH_RSS_IPV4 | ETH_RSS_FRAG_IPV4 | ETH_RSS_NONFRAG_IPV4_TCP | ETH_RSS_NONFRAG_IPV4_UDP | ETH_RSS_NONFRAG_IPV4_SCTP | ETH_RSS_NONFRAG_IPV4_OTHER | ETH_RSS_IPV6 | ETH_RSS_FRAG_IPV6 | ETH_RSS_NONFRAG_IPV6_TCP | ETH_RSS_NONFRAG_IPV6_UDP | ETH_RSS_NONFRAG_IPV6_SCTP | ETH_RSS_NONFRAG_IPV6_OTHER | ETH_RSS_L2_PAYLOAD | ETH_RSS_IPV6_EX | ETH_RSS_IPV6_TCP_EX | ETH_RSS_IPV6_UDP_EX | ETH_RSS_PORT | ETH_RSS_VXLAN | ETH_RSS_GENEVE | ETH_RSS_NVGRE)

  DEV_RX_OFFLOAD_CHECKSUM = DEV_RX_OFFLOAD_IPV4_CKSUM | DEV_RX_OFFLOAD_UDP_CKSUM | DEV_RX_OFFLOAD_TCP_CKSUM
  DEV_RX_OFFLOAD_VLAN     = DEV_RX_OFFLOAD_VLAN_STRIP | DEV_RX_OFFLOAD_VLAN_FILTER | DEV_RX_OFFLOAD_VLAN_EXTEND

  # rte_distributor_alg_type
  RTE_DIST_ALG_BURST     = 0
  RTE_DIST_ALG_SINGLE    = 1
  RTE_DIST_NUM_ALG_TYPES = 2
end
