require "./lib_dpdk"

require "./dpdk/core"
require "./dpdk/constants"
require "./dpdk/constants_extras"
require "./dpdk/packet_constants"
require "./dpdk/asm"
require "./dpdk/llvm"
require "./dpdk/natives"
require "./dpdk/macros_defines"
require "./dpdk/macros_overrides"
require "./dpdk/macros_overloads"
require "./dpdk/inlines"
require "./dpdk/extras"
require "./dpdk/units"
require "./dpdk/debug"
